using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MyTestGenerator
{
    [Generator]
    public class MyGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new MySyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is MySyntaxReceiver _))
                return;

            var contents = @"// <auto-generated>
// Generated by a source generator example
// </auto-generated>

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MyTestGenerator.GeneratedTests
{
    [TestClass]
    public class GeneratedUnitTests
    {
        [TestMethod]
        public void ThisTestWasWrittenByASourceGenerator()
        {
            Assert.AreEqual(2, 2);
        }
     }
}";

            context.AddSource("GeneratedTests.cs", SourceText.From(contents, Encoding.Default));
        }
    }
}




